// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCigDuR0aJ6hcxdixLo6DvmOEAiWj622eY',
    appId: '1:117330215700:web:79e716b8879e725254b801',
    messagingSenderId: '117330215700',
    projectId: 'noire-planner',
    authDomain: 'noire-planner.firebaseapp.com',
    storageBucket: 'noire-planner.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIROKjeIm1_a46Xd4Dbv9FSYEszS_dvBI',
    appId: '1:117330215700:android:92b09521bf85a5d054b801',
    messagingSenderId: '117330215700',
    projectId: 'noire-planner',
    storageBucket: 'noire-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD870SaJjfADBEDGp6LUhYgd6l6ldIUTZA',
    appId: '1:117330215700:ios:0064a3674d056b1f54b801',
    messagingSenderId: '117330215700',
    projectId: 'noire-planner',
    storageBucket: 'noire-planner.firebasestorage.app',
    iosBundleId: 'com.example.noirePlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD870SaJjfADBEDGp6LUhYgd6l6ldIUTZA',
    appId: '1:117330215700:ios:0064a3674d056b1f54b801',
    messagingSenderId: '117330215700',
    projectId: 'noire-planner',
    storageBucket: 'noire-planner.firebasestorage.app',
    iosBundleId: 'com.example.noirePlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCigDuR0aJ6hcxdixLo6DvmOEAiWj622eY',
    appId: '1:117330215700:web:e870e657083c95e954b801',
    messagingSenderId: '117330215700',
    projectId: 'noire-planner',
    authDomain: 'noire-planner.firebaseapp.com',
    storageBucket: 'noire-planner.firebasestorage.app',
  );
}
